### ISSUE TITLE
Confirmation mail after registration, no redirect to original application that triggered the registration

### ISSUE THREAD

**Issue by paulvanbladel** [cloudscribe/cloudscribe#371]
Joe, question regarding confirm mail after registration when the user registers via an oauth client app.
So, user first comes to the Cloudscribe login screen, but selects register and receives confirmation mail. The link in that mail redirect to cloudscribe but that can be confusing for a user. He would expect to be redirected to the custom app. Not sure if this is possible, but the initial register screen received a returnurl towards the originating app. Could that info be used in the confirm mail in one way or another?

**Comment by joeaudette** [comment]
@paulvanbladel I've implemented changes to pass the returnurl through the email confirmation process and published new nugets that should be indexed and available within an hour for you to test and confirm.

I added an input on the page that indicates email confirmation is required (after sending) and added the confirmation code into a textarea in the email message so it can be copied and pasted from the email into the input, though it is a big long ugly code. By copy pasting it into the form the process is seemless in terms of redirecting the user back to the calling app in my samples.

I also appended the returnurl param into the link in the email so if the user clicks the link and a returnurl exists it goes straight to the login page and keeps the returnurl param. In my samples using the link is a little less seemless because the redirect is supposed to be inside the popup login window but clicking the link in the email doesn't get you back into the popup. It does redirect you back to the calling app and if you click the sign in button again in the calling app you find you are already logged in immediately upon clicking the button.

**Comment by paulvanbladel** [comment]
@joeaudette I check this out as soon as I got email sending itself working again.

**Comment by paulvanbladel** [comment]
@joeaudette This works like a charm. I tested from my VueJs app (which doesn't use popups for auth, so I'm not hitting your issue) both the url link approach as well as the code approach work. 
Since the url approach is sufficient for my spa, I'm considering to override the relevant views in such a way the copy/paste code stuff is not visible. Also that is a piece of cake in cloudscribe !
Thanks a lot Joe !
