### ISSUE TITLE
KVP additional validation possibilities 

### ISSUE THREAD

**Issue by blaataap** [cloudscribe/cloudscribe#385]
Hi,

I've been watching this project for a while since im very interested in the process. Im looking at the libraries used and was messing around with KVP to add custom registrations fields. This seems to work very nice but i'm wondering if its possible to extend this having custom validations?
For example if we take the DisplayName attribute we are able to add this to registration/edit/admin forms but what if we want to make this field unique? 

Im not asking for a complete solution but wondering how i would go about extending cloudscribe/KVP to get such thing done?

Thanks

**Comment by joeaudette** [comment]
I think you could just add custom javascript to include for custom validations. Since you can use custom views per item you could decorate the input with some data-* attributes and use js to detect those and wire up validation to check on blur against an api to know if the value is already in use. You would have to write your own api service since cloudscribe does not require unique display names. 

For server side validation you could sub class the handlers like [KvpRegistrationHandler](https://github.com/cloudscribe/cloudscribe.UserProperties.Kvp/blob/master/src/cloudscribe.UserProperties.Kvp/KvpRegistrationHandler.cs) and plugin your custom one and override the validation method.

**Comment by blaataap** [comment]
Yea i used the IHandleCustomRegistration to handle the server side validation. Maybe ill look into adding a KVP property called unique that does both server and client side validation.
