### ISSUE TITLE
Dynamic website creation

### ISSUE THREAD

**Issue by MikeyUchiha** [cloudscribe/cloudscribe#412]
Hi @joeaudette,

I was wondering if there's a way for a new client/customer to create a new website/installation of their own when registering dynamically.

Also, is it possible for a client/customer to completely customize their own website using CSS?

Thanks

**Comment by joeaudette** [comment]
@MikeyUchiha there is nothing built in to cloudscribe core to enable random users to provision sites, nor is there anything built in for users to edit css from the ui or upload themes.

Those things are possible to build separately.

Eventually I might build something to have a demo site where people can self provision a new tenant as a private demo. But if I ever build that I doubt I will make it open source.

Also consider that when using features like cloudscribe SimpleContent, users with edit permission can add javascript to a page which can be used for malicious purposes so it is for "trusted" users, I would not encourage letting random strangers have edit access and would not use cloudscribe SimpleContent as a foundation for a social media site or for letting random people have a blog or editable pages. There are completely different requirements for letting un-trusted users add content to a site, it requires a lot more constraints and limitations and thought on what should be allowed.

**Comment by MikeyUchiha** [comment]
Hi Joe,

Thanks for the response. I'm not referring to "not trusted" users. I'm referring to someone who has registered on my Cloudscribe instance using IdentityServer4. I want to dynamically create a new Cloudscribe site for them with a subdomain. They would therefore be trusted users who have a login account to my main Cloudscribe instance and I can manage their login access to their own created Cloudscribe website through it as well.

Thanks

**Comment by joeaudette** [comment]
A trusted user is someone you know well enough to trust. Someone registering on your site does not make them trusted, a hacker can register on your site.

**Comment by joeaudette** [comment]
I tell you this because it is my definition of trusted user that I had in mind while developing simple content and who it is designed for. I would not build it the same for untrusted users who do not meet that definition. 
It would be ok if using different domain names for tenants and the domain is owned by the registered user but certainly for folder name tenants which use the same domain there are major risks if you have a different definition of trusted user. Therefore if using folder tenants you should understand that letting people who you don’t know and trust have access to simple content editing features, that is definitely a bad idea in my opinion.

**Comment by MikeyUchiha** [comment]
Joe,

Understood. Thank you for the clarification! I'll think of other options.

Thanks
