### ISSUE TITLE
Referencing Blog View

### ISSUE THREAD

**Issue by tmutton** [cloudscribe/cloudscribe#428]
Hello, I am looking to implement a pattern whereby the blog view can be returned in the home index controller. Could someone advise how this can be done?

Thanks

Tom

**Comment by joeaudette** [comment]
Hi,

You can make the blog the default route instead of the home controller, so the blog post list would be your home page. Is that what you are trying to do?

If you really want to use a home controller, we have a viewcomponent for Recent Posts, and another one for Featured Posts, those can be embedded in the home index view.

When you create a project with our [project template](https://marketplace.visualstudio.com/items?itemName=joeaudette.cloudscribeProjectTemplate), there is an option for "Blog Only with Blog as default route". That one setups up the blog as the default route ie with the blog as the home page.

**Comment by tmutton** [comment]
Hi @joeaudette,

Apologies for the delay in getting back to you.

What I'm looking to do is use the same view the /blog route uses for the default home route as 1. I don't have any useful content for a homepage and 2. I like the blog view as a default landing page.

Your suggestion to use the "Blog Only with Blog as default route" looks like it's the solution I need so thank you for that. Should have noticed that option really; for some reason I was only playing with the top two.

Thank you for your help with this
