### ISSUE TITLE
After I updated to latest version I got handled 404 for url: /js/bootstrap4.bundle.min.js

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe#445]
I found references to that file in:
`Blog.Views.dll`
`cloudscribe.Core.CompiledViews.Bootstrap4.Views.dll`
and in a lot of `_Layout.cshtml`

**Comment by joeaudette** [comment]
In previous versions I had renamed the bootstrap.bundle.min.js to bootstrap4.bundle.min.js but in the latest template I changed that for custom1 theme to use the standard names.
The SharedThemes do still have files named that way but the files exist in the wwwroot folder of the theme and are still named that way.

The bad url may still exist in _Layout file of cloudscribe.Core.CompiledViews.Bootstrap4, I will fix that but that file is never used since the template includes _Layout files in the local project that would always override the one in the nuget.

If you have a custom theme and you don't have the bootstrap files in the wwwroot folder of the theme, then you should just edit your _Layout file and change it to bootstrap.bundle.min.js without the "4"

**Comment by cheverdyukv** [comment]
Hi Joe.

I don't know how it happened but but all my sites have theme default.  After some checks I found that custom1 and SharedThemes are not used so I stopped deploying them.  But looks like it is not supported. So what is best way to fix it for me? Switch to custom1 theme or one of standard themes?

**Comment by joeaudette** [comment]
I would copy the boostrap js and jquery js from the latest template wwwroot/js folder into your project and change the reference in your layout to point to those. Note that jquery was also updated to the latest version in the template and bootstrap was updated to latest 4.1.2.
Similarly if you have not modified the bootstrap css and are just using the default I would copy that from the wwwroot/css folder in the latest template

**Comment by joeaudette** [comment]
custom1 theme is best because is uses scss version of bootstrap from node_modules andl allows you to plugin variables to customize bootstrap. There is a gulpfile in the tempalte with tasks that process the scss aka sass into css.

**Comment by joeaudette** [comment]
I use custom1 for all my projects and change colors etc per my client wishes

**Comment by joeaudette** [comment]
I see it is a bug in the template, "default" just means it is using the _Layout from Views/_Layout (instead of from a theme folder) and I forgot to update that one because new projects are initialized to use custom1 so I didn't notice it. I will fix that. You can fix it in your copy easily by remove the 4 from the js reference.

**Comment by joeaudette** [comment]
I will update the layout for default theme to include cookie consent. But really that is meant as a fallback, I think most people use a custom theme and not default bootstrap styles.

I highly recommend use custom1 and don't be afraid to experiment with changes.
In TaskRunnerExplorer you can run the gulp task after any changes to the app_scss/* files, you can change colors etc there.
The default gulp task actually starts a file watcher then it will auto regen the css whenever you make changes to the scss files, so you can just edit and refresh the page.

**Comment by cheverdyukv** [comment]
Thanks I will do it.
