### ISSUE TITLE
Site name not updating until app pool recycle

### ISSUE THREAD

**Issue by StewartBellamy** [cloudscribe/cloudscribe#516]
When I go into Site Settings and change the Site Name and save it, it does not immediately take effect.  If I recycle the app pool the updated Site Name then appears on the header.

**Comment by mfoitzik** [comment]
Hi Joe. After my pull request that fixed the issue with the theme changes not showing up, I noticed that even though it fixed the issue on my development machine, the problem is still there when I deployed to a host. I think the issue (related to this issue submission) is that the site context is cached and that it is not getting properly cleared in SiteManager.cs or there is something else going on.

I am starting to think that within the context of Cloudscribe that sitecontext should not be cached because of the user/tenant specific info that it contains. On the ASP.NET Core doc page on Microsoft's site (https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response?view=aspnetcore-2.1) The following warning is highlighted:
Warning
Disable caching for content that contains information for authenticated clients. Caching should only be enabled for content that doesn't change based on a user's identity or whether a user is signed in.

**Comment by joeaudette** [comment]
@mfoitzik your [pull request](https://github.com/cloudscribe/cloudscribe/commit/c6b0dced3fc4ad4988306c3ddbde1ec1500bc3a8) did introduce this bug

we do need to use the request host name to clear the cache and you removed that. Preferred hostname is usually blank especially for a single tenant installation, there is no requirement to populate it or any host name except when there are multiple tenants but even then the root site doesn't require any host name. The site context for host name gets cached using the actual host name in use at the time it is cached.

That article you mention is about html response output caching which is something completely different thing than caching an entity to avoid hitting the db to hydrate it on every request. 

This issue should now be fixed as I've restored the logic to clear the cache by host name of the request.

https://www.nuget.org/packages/cloudscribe.Core.Web/3.1.29
