### ISSUE TITLE
I have a lot of warning in log AcceptLanguageHeaderRequestCultureProvider returned the following unsupported cultures 'en'.

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe#537]
Hi

I periodically checks System log and there often entries like this:
warn: Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware[1]
      AcceptLanguageHeaderRequestCultureProvider returned the following unsupported cultures 'en'.
warn: Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware[2]
      AcceptLanguageHeaderRequestCultureProvider returned the following unsupported UI Cultures 'en'.

I'm not sure what header value it uses but for Accept-Language and for Content-Language 'en' is valid language id. Would it be better if in this case it fallback to en-us?

**Comment by joeaudette** [comment]
That is logged by Microsoft if the browser accepted language is not one of the supported languages.
In the cloudscribe project template you control the supported languages in the /Config/Localization.cs file and you could add en there as supported. 

Typically the default language should be more specific then en because it is used for formatting numbers and dates and en-US indicates currency and date formatting, ie en-GB would have different currency and date formats than en-US so which one should en use? I have no idea and no control over that so best to use a more specific setting for default.

en-US is more specific than en so I would never expect it to fallback to en-US for en if en is not supported, it could fallback to en for en-US maybe at least for string resources but not for dates and number format.

In any case that is just a warning and noise in the log, since it will only use a supported language you have configured you can safely ignore that warning. I would not change it to make the warning go away, because the browser should not decide for the server that it should use a less specific setting.

I would filter that from logging by adding it in the ExcludedNamespaces for DbLoggerConfig

**Comment by joeaudette** [comment]
In other words the server is only going to use either a configured supported language or the configured default language no matter what the browser accepts. So if the browser passes en and en-US is the default and en is not supported then it will use en-US so in that sense it kind of falls back in that it falls back to the default anytime the requested language is not one of the supported languages.

**Comment by cheverdyukv** [comment]
Thank you it helped for system log
I there any config that I can remove from logs directory on server? I did try to put it in BelowWarningExcludedNamesSpaces like this:
    "BelowWarningExcludedNamesSpaces": [
      "Microsoft.AspNetCore.StaticFiles",
      "Microsoft.AspNetCore.Hosting",
      "Microsoft.AspNetCore.Authorization",
      "Microsoft.AspNetCore.Mvc.Internal",
      "Microsoft.AspNetCore.Localization"
    ]

but it didn't work.
