### ISSUE TITLE
Email Messages Enhancements 

### ISSUE THREAD

**Issue by abomadi** [cloudscribe/cloudscribe#554]
Editing email theme design in real time.

**Comment by joeaudette** [comment]
Html email design is very hard, much harder than regular web html design. I'm not really a web designer myself and I don't expect to build web design tools anytime soon. Also the email templates use razor views and layouts which must be compiled after editing so that would be a difficult thing to do dynamically with editing in the browser. Not impossible but a lot of challenges that I don't care to take on any time soon given all the other things I do plan to work on.

I'm going to close this since I don't have plans at this time to try to build such a thing.

My advice for the moment is override email razor views and layouts in the app and have a web designer make them look how you want.
