### ISSUE TITLE
Related sites mode issue

### ISSUE THREAD

**Issue by nirkbirk** [cloudscribe/cloudscribe#556]
Hi Joe,

Really enjoying working with cloudscribe, but I've run into an issue I can't seem to get around. I'm running in Multi-tenant "FolderName" mode with UseRelatedSitesMode set to true. I've also set the RelatedSiteId value to the guid of my default 'Sample' site.

It's my understanding from the documentation that with this configuration, all sub-sites will look for users and roles against the 'Sample' site.

I created a new site called test with the folder name '/test' and was a bit surprised to see that I couldn't continue without creating an admin user for this site. I expected it to simply use any admin users that existed on the 'Sample' site. Regardless, I created a new admin user in this form and just carried on.

The new site was created as expected, however, when I tried to log in as the default admin@admin.com account in this site, the login would be successful and redirect me back to the home page, but would still present me with the login/register buttons and provide no admin panel link, nor any CMS options from SimpleContent. The authentication cookie is definitely being set, and logging out from the main site and then going through login on the child site is setting the cookie correctly - navigating back to the main site provides the expected CMS options and admin panel access.

Furthermore, when I try to login as the new admin user I created along with the sub site, I get an invalid user message. After some poking around, I found that this user was created against the site id of the test site, and isn't even visible in the Sample site's user list. 

So with that background out of the way, I have two questions:

1) why is a new admin user required for new sites in UseRelatedSitesMode? Especially since this user is created against the test site and therefore cannot actually be used to login in this mode. Is it for if UseRelatedSiteMode is disabled at a later date?
2) Am I missing something to get users to be able to login and access CMS/admin capabilities on both sites? I feel like I may just be misunderstanding how this works. We have a similar setup for a mojoportal site though and expected it to work in the same way.

Any light you could shed on these issues would be greatly appreciated.

Thanks

**Comment by joeaudette** [comment]
1. The admin user is always created for any new site, that user will never be used unless you later were to change the settings and not use related sites mode. It gives a way to be able to login as admin if you later decide to change the configuration, but until that time it is not a valid user and you cannot login with that account. That is the same with mojoportal, otherwise if you ever change from using related sites mode then there would be no accounts in the second site an no admin user. But any subsequent users created or registered in the second site (when using related sites mode) should all be attached to the master site id.

2. With related sites mode after you create the second site you should be able to login to it with the admin user credentials from the first site ie the related site and you should have admin privileges. If you are saying that is not the case I will investigate it.

**Comment by joeaudette** [comment]
ok, just testing it here and seeing it isn't working as it should, investigating it now.

**Comment by joeaudette** [comment]
Thanks for the bug report, this is now fixed if you update to the latest cloudscribe nugets.
https://www.nuget.org/packages/cloudscribe.Core.Web/3.1.47

In fact with folder tenants and related sites mode, if you are logged into the root site then you are already also logged into child folder sites, so you don't have to login to the folder sites separately. If using host name tenants then you would have to login to each site separately but using the same credentials.

**Comment by nirkbirk** [comment]
Wow, very quick response & solution. Thanks a lot Joe. 

Cheers

**Comment by joeaudette** [comment]
fyi, I just published updated nugets for the views, I added a message on the new site view about the purpose of creating an admin user when creating new sites in related sites mode to make it less confusing.
