### ISSUE TITLE
File manager page included in sitemap feed

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#588]
mysite.com/api/sitemap
includes
```xml
<url>
<loc>
mysite.com/filemanager/index
</loc>
</url>
```

**Comment by joeaudette** [comment]
If you logout and view it as google sees it it will not be there because it is filtered by an authorization policy.

In general I also add excludeFromSearchSiteMap="true" to the node in navigation xml but missed it for that one. That will filter it out even when logged in and meeting the policy. I just added it in the project template so it will be in the next template update. But not urgent to release since it isn't really showing that to google or to any user who does not meet the policy.
