### ISSUE TITLE
Microsoft Identity Platform or Azure AD B2C

### ISSUE THREAD

**Issue by varghesep** [cloudscribe/cloudscribe#603]
This is an information question only, and not a defect. I have used ASP.Net Membership Provider for ASP.net applications before and just getting familiar with OAth and OpenID.

I was researching on supporting a user identity management feature, authentication and authorization for a SPA.

These are the requirements:

- There will be groups, admins and users. The admins should be able to manage users like turning their access on or off.
- The user should be able to login to the SPA application and have only read-only access
- The admin should be able to update the data in the SPA

I took the route of using [Azure AD B2C](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps) but then stumbled upon cloudscribe. Can someone explain the benefits that I can get out of cloudscribe compared to Azure B2C?

**Comment by joeaudette** [comment]
I moved this issue from the cloudscribe SimpleContent repo to this on e for cloudscribe Core since your question is about cloudscribe Core.

When used with our IdentityServer4 integration cloudscribe can provide a complete openidconnect solution. cloudscribe Core provides the user management with ability to manage roles and claims for a user, and IdentityServer4 provides the handling of openidconnect protocols and issuing of jwt tokens.

So those combined capabilities allow you to stand up your own openidconnect provider service that is roughly equivalent of AzureAD since AzureAd is an openidconnect provider.

Additionally you can federate more than authentication provider. For example you can allow users to login with social auth by federating social auth providers together with IdentityServer4. Social auth providers are themselves openidconnect providers and you can even use AzureAD as an openidconnect provider with cloudscribe core by configuring the settings for openidconnect under Administration > Social Logins. So by federating I mean combining all under one, you can have AzureAD, Facebook, Microsoft, Twitter etc as well as regular accounts that just register with a username/email and password.


All of these things are openidconnect providers:
AzureAD,
[Okta](https://www.okta.com/)
Facebook auth,
Twitter Auth,
Microsoft Auth,
Google Auth.

cloudscribe provides dedicated settings for configuring social auth as well as one set of settings for configuring any generic openidconnect provider such as AzureAD, Okta. and with our IdentityServer4 integration you get one login page that can handle all of that for any spa app that you configure as a client and apis that the client will access. Our integration with IdentityServer4 provides management pages for configuring clients, apis, and identity resources which is a complex topic, I don't claim to be a super expert on all the settings and flows supported by IdentityServer4 so would refer questions about it to their documentation.

By standing up your own openidconnect service with cloudscribe Core and IdentityServer4 then you may not even need AzureAD or any other service so you can potentially save money on service fees. But if you have other reasons for using AzureAD you can also use that with cloudscribe as a generic openidconnect provider.

So think of it as something that can be both an alternative to or an integration point for AzureAD.
We have some samples with spa clients here that can help you evaluate whether it will meet your needs: https://github.com/cloudscribe/sample-idserver
