### ISSUE TITLE
Bug Report. File manager remembering last file upload on upload tab

### ISSUE THREAD

**Issue by hsankala** [cloudscribe/cloudscribe#622]
Hey Joe, little bug report for you.

To reproduce, create vanilla CS site created with CS proj template with all CS nuggets up to date.  Go to admin -> File Manager, create new folder called 'Test'

First issue
---------------
Attempt to upload 26 images to folder in the upload tab, by drag and drop
**Issue**  Only ten files listed after dropping them in.

Second issue
--------------
`Upload` the 10 the ten images, then attempt to drag and drop the next ten images (in case there is a upload file number limit of 10 imposed)
**Issue** The first set of ten image names re-appear, selecting the `upload` button does nothing.  Full page refresh required to upload more.

**Comment by joeaudette** [comment]
I have fixed the second issue and published updated nugets.

Currently it does limit to 10 files at a time and isn't currently configurable. I'm open to making that configurable if you'd like to open a new issue requesting that enhancement. But it needs some thought since files can be uploaded by users of varying privilege level, I can see allowing admins to upload more but it will be more complicated to allow admins to upload more without allowing everyone to upload more.

**Comment by hsankala** [comment]
Sweet Joe looks good.

My only suggestion would be to surface a message to the user if they are over the upload file limit for that operation, to give the user some feedback to what is going on.

**Comment by joeaudette** [comment]
After giving it more thought I decided to remove the 10 file limit. If a user has permission to upload files and they want to upload 100 files, that limit just means they have to do 10 separate uploads, in fact there is no real limit since they can upload as many times as they want to, so it really wasn't doing anything other than hurting UX. The main thing is that only trusted users should ever be given file upload permission.

Also I've removed the Upload button and configured it to auto upload on file selection because I found that when using the button to trigger upload, all the files were uploaded in a single post to the server and that increases the odds of bumping into the server maxrequestlength since the size of all the files would count towards that. With the auto upload on select option each file is uploaded with a separate request.

**Comment by hsankala** [comment]
Cool, one suggestion might be an idea to add some more user feedback for a successful upload (like small message '3 files uploaded successfully').  For small files uploaded on a fast connection the upload can almost appear instantaneous, just a quick flash of a progress bar.  This could lead the user to attempting the operation again (it did with me, but I was used to having the upload button).

**Comment by joeaudette** [comment]
Good idea, I've added upload success notification and published again.

**Comment by joeaudette** [comment]
might be a few minutes before the new nugets are indexed.
