### ISSUE TITLE
it would be nice to have new user notification without require approval

### ISSUE THREAD

**Issue by joeaudette** [cloudscribe/cloudscribe#647]
followup related to #646

It would be nice to support new account notification even when not requiring account approval.
The same setting for notification email csv could be used, but sending a different message just notifying that a new user has registered.
Having this functionality could provide a better user experience than requiring approval for new accounts because the user could be allowed immediate access with minimal permissions and the the admins once notified could grant the user additional roles if they 'approve' of the user. From the user's point of view this would seem less obnoxious than making them wait for account approval before they can login,

**Comment by SimonAnnetts** [comment]
cloudscribe.Core.CompiledViews.Bootstrap4.4.0.5.nupkg
cloudscribe.Core.Web.4.0.6.nupkg
Created and Uploaded to nuget.org

**Comment by CrispinF** [comment]
Test plan:

1. "Require confirmed email"=0 , "Require approval before login"=0 > notification email should be sent if email address(es) configured. Also test same if emails not configured, to check things work.
2. "Require confirmed email"=0 , "Require approval before login"=1 > approval notification email should be sent if email address(es) configured. Also test same if emails not configured, to check things work.
3. Text label changed on Security Settings page?

Results:

1. Notification email received. Pass.
If email not configured, registration appears to fail - user gets an error, but their account is created. Fail. Registration should succeed without an error.
If email configured in the tenant, but not in the main site, we get the same outcome: error.
If email configured in the main site, registration succeeds.
So the email notification setting is always using the email addresses setting from the main site, even though it appears you can configure it in the tenant. Is this as intended? Need to compare to other behaviours.

2. Approval notification email. Pass.
If no email configured > Fail!  Registering user gets an error on registering, and their account is not created.
Need to log a new issue for this, but these settings below cause an error for end users. Preferably this situation should be blocked in the settings page, but in any case registration should proceed without error and create the account (pending approval).
![image](https://user-images.githubusercontent.com/10574730/79632601-469cae80-8158-11ea-957e-7691c7c6a3e7.png)
The error is 18/04/2020 09:35:23 Error 31.125.xx.xxx Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware /librarylink/account/register
An unhandled exception has occurred while executing the request.&#xD;&#xA;System.NullReferenceException: Object reference not set to an instance of an object.&#xD;&#xA; at cloudscribe.Core.Web.Components.Messaging.SiteEmailMessageSender.AccountPendingApprovalAdminNotification(ISiteContext siteSettings, IUserContext user)

3. Label changed - Pass (nearly). However I don't see the new string in the CloudscribeCore.*.resx files.

Exploring more about tenancy. My test site is in this mode:
  "MultiTenantOptions": {
    "Mode": "FolderName",
    "UseRelatedSitesMode": "true",
and the "RelatedSite" is my s1.

**Require approval configured in main site, not in tenant. Emails configured in main, not in tenant.** Registration in tenant > error, account not created.
Registration in main site > succeeded.
**Require approval configured in main site, and in tenant. Emails configured in main, and in tenant (different ones).**
Registration in tenant > succeeded, and used emails from main site.
Registration in main site > succeeded, and used emails from main site.
**Require approval off in main site, on in tenant. Emails configured in main, and in tenant (different ones).**
Registration in tenant > appeared (to the user) to succeed with approval required. Notification sent, and used emails from tenant. _But the account was not created!_ No errors in system log.
Registration in main site > succeeded without approval. Notification sent to emails configured in main site.

There are definite issues to be fixed here, so in the meantime, in cloudscribe.Core.Web 4.0.6 the recommendation has to be: 
a) always configure notification email addresses if your site permits registration of new users.
b) if working in UseRelatedSitesMode=true then ensure the requirement for approval is set the same in all tenants (which seems sensible anyway!).

**Comment by CrispinF** [comment]
Important correction to test results:
**Require approval configured in main site, and in tenant. Emails configured in main, and in tenant (different ones).**
Registration in tenant > appeared to succeeded, and used emails from tenant, but _the account was not created._
Registration in main site > succeeded, and used emails from main site.
So registration is failing in child tenant sites when UseRelatedSitesMode=true.
We need to test whether this was working before the changes for 4.0.6, and resolve this asap.

**Comment by CrispinF** [comment]
I can confirm that registration in a child tenant also failed in cloudscribe.Core.Web 3.1.100 in exactly the same multi-tenant configuration, so this is not a recent breakage. I will move this to a new issue.

**Comment by CrispinF** [comment]
To summarize: we have a bug in registration in tenants, but it's not caused by this change. #705 

We have a new problem introduced by this change, which is that new registrations _appear_ to fail if notification emails are not configured, even if no approval is required. In fact the new account is created, but the end user sees an error. This needs to be fixed and a new package released.

We have another problem that may have already existed: if approval is required, but no email configured, registration fails and the account is not created. That is obviously a configuration error, but it could be handled better.

We have a weakness around the design wrt sending confirmation to new users of approval > #704 

We have significant confusion around which site settings are used in multi-tenant UseRelatedSitesMode mode. I've seen it use the configured emails from both the master and the tenant in different scenarios. There may be a case for saying that when in UseRelatedSitesMode only the master site's settings should be respected, and the configuration page in the tenant should reflect this by being disabled. Need to reflect on this.

We may have a minor correction needed to the above work to make the resx match the updated label, but first we need to check how these are delivered with a package is updated - the resx in my test site may be from its initial setup?

**Comment by SimonAnnetts** [comment]
updated to cloudscribe.Core.Web.4.0.7

**Comment by CrispinF** [comment]
@SimonAnnetts I can confirm that a null notification email address now does not prevent registration succeeding.
And that the notification works nicely if an address is configured (with each tenant using its own configured email).
Just one improvement: when a null email is found, but clearly should be present because "Require approval" is set, I think we should log an Error (or Warning?) that no notification email address was found.  Could you possibly add that and push a new version @SimonAnnetts  thanks!

**Comment by SimonAnnetts** [comment]
bumped cloudscribe.Core.Web to 4.0.10

**Comment by SimonAnnetts** [comment]
documentation updated at https://www.cloudscribe.com/cloudscribe-core
