### ISSUE TITLE
Creating Project With New Template in VS2017 Defaults to NETCore 3.0

### ISSUE THREAD

**Issue by Disflippant** [cloudscribe/cloudscribe#681]
Hi

When creating a new project with the template in VS2017, you don't have the option to select the NetCore framework, and the project defaults to trying to use NetCore 3.0.  Trying to get it to use netcore 2.2 via csproj editing and nuget manager becomes a knotted nightmare of compatibility errors. Should the template work for a Netcore 2.2 project? If so, how do we get it to load and set dependencies for that framework?

Regards

**Comment by joeaudette** [comment]
The latest project template only supports .NET Core 3. In fact it is a bug that it can be installed in VS 2017, I need to change compatibility to only VS 2019 since that is required for .NET Core 3.

I made a copy of the last version of the template before the 3.0 updates and you can download it here: https://www.joeaudette.com/cloudscribeTemplate-1.85.zip

So the steps would be uninstall the one you have, download the old one and extract it from the zip file and install that one. It will setup projects for .net core 2.2. But you won't be able to use the latest cloudscribe nugets unless you go for using .NET Core 3 and the newer template with VS 2019.

**Comment by Disflippant** [comment]
Thanks for the response..
