### ISSUE TITLE
Uploading images with different language name

### ISSUE THREAD

**Issue by abomadi** [cloudscribe/cloudscribe#688]
Uploading images with Arabic for example names is not allowed by the file upload manager, also date inputs as well

**Comment by joeaudette** [comment]
@abomadi @CrispinF 

The file upload code is part of cloudscribe.FileManager.Web in the cloudscribe core repo. I have transferred this issue here.

The way to investigate this would be to:
* Get the cloudscribe core solution working on your machine
* Add ar-JO as supported culture and temporarily set as the default culture
* try to replicate the error by editing content (drag drop and file manager)

**Comment by joeaudette** [comment]
edit culture settings in Configuration/Localization.cs

for testing, alternatively, leave en-US as default culture in web app but set browser culture to ar-JO

**Comment by abomadi** [comment]
![image](https://user-images.githubusercontent.com/5151487/74641366-d5ea0d80-5179-11ea-8e4b-bd49f6f2ae6c.png)

@CrispinF @joeaudette  this is the issue, the image name is written in arabic with - in between and the extension is .jpg, it gives this error message, this only appears on file manager, if we are using direct upload it works!

**Comment by abomadi** [comment]
@joeaudette @CrispinF also regarding the date, when the culture is ar-Jo or any ar the dates are shown in arabic numbers, when saving them it gives the below error
![image](https://user-images.githubusercontent.com/5151487/74641758-7ccea980-517a-11ea-8b3f-11994f462900.png)

**Comment by CrispinF** [comment]
@abomadi we'll look at the File Manager issue soon. 
Can you explain where you see the date input problem? I might make a new issue for that.

**Comment by JimKerslake** [comment]
I can recreate the issue with the file manager image upload.  
You don't need to be running cloudscribe in Arabic culture - it happens regardless.
There is no logged error - the issue is in the JavaScript - 
a regex check for image filename validity doesn't make provision for Arabic characters.
I'll make a candidate fix and post back here again when it's done.
-- jim

**Comment by JimKerslake** [comment]
If I have followed this correctly, then I think I'll need to push new versions of nugets up the chain as follows:
cloudscribe.FileManager.Web up to v 4.0.2
cloudscribe.FileManager.CoreIntegration up to v 4.0.2
cloudscribe.Core.Web up to v 4.0.5

**Comment by JimKerslake** [comment]
That's done now and available for test by updating to the new version of cloudscribe.Core.Web 4.0.5
(I looked at the file upload only, so far)

**Comment by JimKerslake** [comment]
I can also reproduce the problem of the date entry box - which only occurs when in Arabic culture.

This seems like a server-side model validation error.
There is a Bootstrap DatePicker on the User Info page, for entering Date of Birth.
When in Arabic culture, this continues to show non-Arabic 'picker' elements, but when a date is selected it populates the input box with an Arabic date string.
Posting that back to the UserAdminController, this fails to validate when binding back to the DateOfBirth DateTime property on the EditUserViewModel.
ErrorMessage = "The value '٤/‏٥/‏٢٠٠٩' is not valid for DateOfBirth."
I didn't see any sign that this is due to any custom validation within cloudscribe (I might have missed it though) - I suspect it's just innate to the MVC model binding.

I'm not currently sure how best to address that - whether at the level of the model binding, or the datepicker control.  Perhaps the datepicker could be configured to post back an ISO date format string instead...?

**Comment by CrispinF** [comment]
Let's move the date problem to a new issue.
@abomadi please can you update with cloudscribe.Core.Web up to v 4.0.5 then  test if the file upload problem is resolved?

**Comment by abomadi** [comment]
@CrispinF @JimKerslake  many thanks, it looks just fine
