### ISSUE TITLE
Some CkEditor options in appsettings.json are not being used

### ISSUE THREAD

**Issue by SimonAnnetts** [cloudscribe/cloudscribe#729]
While it is possible to override the CustomConfigFile path in the CkeditorOptions section of appsettings.json, the other options do nothing.

Specifically:

FileBrowseUrl
ImageBrowseUrl
DropFileUrl
VideoBrowseUrl
AudioBrowseUrl
CropFileUrl

These are always being hardcoded in cloudscribe.Core.Web.Components.GetCkeditorOptions.

If the Ckeditor section is present in appsettings.json then it should be possible to override these. If the section is not present (or these options are empty)  then they should be defaulted to the original FileManager controller endpoint.

**Comment by joeaudette** [comment]
Actually this change may have introduced a bug because if those settings do exist in appsettings it will likely break the functionality in folder tenants because the original code which used urlHelper.Action works correctly to resolve the needed tenant folder in the url. So to support folder tenants it is best not to have those in appsettings.

The use of those settings outside of cloudscribe would be more typical but this resolver is specifically for cloudsribe tenants.

**Comment by CrispinF** [comment]
https://www.cloudscribe.com/using-ckeditor currently says there's no need to put these in appsettings unless you have a specific need to do so (which we do in one project).  If we add advice that the defaults are tenant aware, and so to support folder tenants it is best not to have those in appsettings, does that solve any concerns?

**Comment by joeaudette** [comment]
As long as the appsettings we ship in the template does not include those settings it should be fine.

**Comment by CrispinF** [comment]
Tested ok, closing.

**Comment by CrispinF** [comment]
Documentation updated.
