### ISSUE TITLE
Appsetting name typos for site theme settings

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#732]
UserPerSiteThemes should be UsePerSiteThemes 
UserPerSiteWwwRoot should be UsePerSiteWwwRoot
Used in SiteThemeListBuilder https://github.com/cloudscribe/cloudscribe/blob/7c57dc4532236004e732b980945bf391ec5febf0/src/cloudscribe.Core.Web/Design/SiteThemeListBuilder.cs

I'd suggest we keep reading from the old spelling and the corrected, to avoid causing problems for existing sites that are using these settings.

**Comment by JimKerslake** [comment]
As with another example elsewhere, fixing this is probably better regarded as a breaking change... because to continue to support the old mis-spelling would require bespoke code-around to the process by which the default Json deserializer simply maps the appsettings onto a C# class... not really desirable to enshrine historic mis-spellings into future code.

**Comment by JimKerslake** [comment]
This was fixed and incorporated into a breaking change at Core5 major version release
