### ISSUE TITLE
Change user email: unhelpful error message when trying to save already-used address

### ISSUE THREAD

**Issue by JimKerslake** [cloudscribe/cloudscribe#796]
(Perhaps by design?) this does not make it clear when a user is trying to change their email address to one that is already in use in the system. The error is unhelpfully generic.

**Comment by joeaudette** [comment]
If a user tries to change to an email that is already in use and they are
given a message saying the email is in use, it leaks information about
existing accounts. There is no guarantee the user is trying to use an email
he owns. So it should be the same as site registration in that it should
not verify that an account exists.
Probably what should happen is send an email to the email address that the
user is trying to change to with a link that would let them proceed, since
that would verify ownership of the email.

**Comment by JimKerslake** [comment]
Hi Joe 
Yes indeed - agreed - that's why I said 'perhaps by design' ;) 
I had a distant memory that we had discussed that before.
Yep, agreed that would be more sensible.

Hope all's well with you.

**Comment by joeaudette** [comment]
Doing well here, hope you guys are.
Have to admit I don't enjoy working at the bank as much as the old days
working with you guys and cloudscribe, a lot of stress is involved, but it
is helping me save for retirement which I hope to do in 3-5 years.
Free time on weekends I've been doing a lot of Microsoft Flight Simulator
2020 in a Virtual Reality headset. It is an amazingly realistic flying
experience.

**Comment by JimKerslake** [comment]
Fine here thanks, Joe - cloudscribe still forming the bedrock of much of what we do.
Multi-tenancy worked out really well for us in a project recently.
Been a bit immersed in the upgrades to Net5.0 and BS5. 
My own weekends are rather more growing veg and river-swimming :)
I did some real flying once - just made me feel very air-sick though :/

**Comment by CrispinF** [comment]
I just tried to change the email on one of my accounts on cloudscribe.com to that used by another account (also mine), and received this feedback:
![image](https://user-images.githubusercontent.com/10574730/185958358-22b80a45-5377-4421-97e2-8b6268e013c2.png)

**Comment by CrispinF** [comment]
Closing this after through review with @JimKerslake
