### ISSUE TITLE
Implement Google Analytics 4

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#836]
cloudscribe enables GA Universal Analytics once a Google Analytics Tracking Id is entered in site settings.
![image](https://user-images.githubusercontent.com/10574730/193446550-efb0b910-918f-43ad-a273-21951d818b9a.png)

Google says: "Universal Analytics properties will stop collecting data starting 1 July 2023. It’s recommended that you create a Google Analytics 4 property instead."

cloudscribe implementation of GA is described here:
https://www.cloudscribe.com/google-analytics-integration
https://www.cloudscribe.com/easy-google-analytics

**Comment by JimKerslake** [comment]
Quick investigation of this:

the current simplest form of incantation supplied by Google for incorporating the GA tracker is actually identical between the old UA- codes and the new GA4 ones:

```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-JVG2VJVW08"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-JVG2VJVW08');
</script>
```


However just swapping from old to new GA code in CS will not work - 
perhaps because the equivalent of the above code rendered by the tag helper in CS is vastly different - presumably an older version?


```
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
function gaGetCookie(name) {var value = "; " + document.cookie;var parts = value.split("; " + name + "=");if (parts.length == 2) return parts.pop().split(";").shift();}function defaultCookieConsentCheck() {var consentStatus = gaGetCookie("cookieconsent_status");if (consentStatus == "yes") { return true; } else { return false; }}var gacanUseCookies = defaultCookieConsentCheck();ga('create','UA-2323613-17', 'auto', {  });
if(gacanUseCookies) {ga('set','userId','41558c89-388d-43c7-9e7d-748a2142805a');ga('require', 'displayfeatures');ga('set', 'anonymizeIp', undefined);} else {ga('set', 'displayFeaturesTask', null);ga('set', 'anonymizeIp', true);}ga('send', 'pageview');
```


At its simplest level, swapping over to use the above inclusion script would start to work - but (from the documentation links above) the CS implementation supports a lot more sophisticated GA tracking configuration features which may not continue to work as documented... so need to unpick all of those and how they interact with the cookie consent system, etc.

**Comment by JimKerslake** [comment]
...in particular the CS  GoogleAnalyticsApiService  and GoogleAnalyticsHelper (see docs) may or may not continue to function against GA4 endpoints

**Comment by CrispinF** [comment]
We should continue to use the existing Google Analytics Tracking Id Site Setting, and detect whether it begins UA (old Universal Analytics) or not (new Universal).

**Comment by CrispinF** [comment]
Here's the JS that works for UA and GA4:

```xml
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-1M279KJTQD"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-xxxxxxxx');
</script>
```

**Comment by SimonAnnetts** [comment]
Now that I've started reading the Google documentation, this looks like it's going to be a fair amount of work to make this work with GA4.  I suspect a complete rewrite of the tag helper. event and transctions helpers and extensions, and possibly the apiservice too.

1. We are using the old analytics api analytics.js (UA) library and sending events. The data sent with an event hit includes Category, Action, and Label like this:
~~~
ga('send', {
  hitType: 'event',
  eventCategory: 'Settings',
  eventAction: 'Enable',
  eventLabel: 'Dark mode'
});
~~~
For some reason, cloudscribe also has Value field in the event model.

We can update the analytics api library to gtag.js, then for the UA tracking the event needs to become:
~~~
gtag('event', 'Enable', {
  event_category: 'Settings',
  event_label: 'Dark mode'
});
~~~
It's still possible within google admin pages to link UA collected data to GA4 data so you can see UA data in GA4. This will only work until UA is phased out.
In order to move fully to GA4 we need to be using the gtag.js library and change events to look like this:
~~~
gtag('event', 'settings_update', {
  setting: 'mode',
  status : 'dark'
});
~~~

Some of the custom events we are using in UA are now standard/enhanced events in GA4, so where possible we should be mapping to the pre-defined GA4 event.

Documentation for this is here:
https://developers.google.com/analytics/devguides/migration/measurement/events#gtag.js-ua

2. There is code in cloudscribe currently that sets up analytics.js (UA) library with cookie consent settings. Not sure how this will work in gtag.js (GA4)
3. We also send ecommerce transactions using ga('ecommerce:addTransaction', {id, affiliation, revenue, shipping, tax, currency} and   ga('ecommerce:addItem', {id, name, sku, category, price, quantity, currency} with a final ga('ecommerce:send'); This will need to change to a GA4 purchase event.
https://support.google.com/analytics/answer/11986666?hl=en#purchases&zippy=%2Cin-this-article
4. Some events like pageview have a set of properties. Need to check if these are all the same!

**Comment by SimonAnnetts** [comment]
I think the safest way forwards here is to write a new tag helper that is very basic at first and just adds to the new gtag.js script to the page. We also need to change the analytics.js tag helper to become disabled if the Google Analytics Property key starts with a 'G-' rather than the older 'UA-'

**Comment by SimonAnnetts** [comment]
First attempt with a new tag helper module Analytics.GA4. It's completely independent of the the existing Tag Helper and attempts to push the same (equivalent) events to Google as the old Tag Helper. Event names have changed however, but we do use Google recommended event names where they are available. Event names can be customised in the appsettings.json file as per the original tag helper.
Ecommerce data is not dealt with yet.... need to see if that is worth the effort?
Also there is no remote API endpoint for this... It was used as a hack to get events from social logins to work... and also to allow external apps or services to push events. It used it's own Http client to send events to Google. Not sure if GA4 supports this!

**Comment by SimonAnnetts** [comment]
There are still two tag helpers. Existing:
~~~
<google-analytics profile-id="@Tenant.GoogleAnalyticsProfileId" user-id="@User.GetUserId()"></google-analytics>
~~~
and the new one:
~~~
<google-analytics-ga4 profile-id="@Tenant.GoogleAnalyticsProfileId" user-id="@User.GetUserId()"></google-analytics-ga4>
~~~

however the existing tag helper will switch to use the new GA4 tag helper if the GoogleProfileId set in the site settings begins with a 'G'.

The event handlers dotted through the AccountController.cs remain the same, but they two will switch to GA4 as above.
There are two new event handlers:
'logout' and 'search'.
logout has a reason parameter which can be 'User Signed Out' or 'Federated User Signed Out' or 'Login Timed Out'
and search provides the search query string and the number of results.

I've also tested with Google login and the login event does include that the method='Google'.

**Comment by SimonAnnetts** [comment]
cloudscribe.Core.Web version is now 6.0.16
cloudscribe.Web.Common version is now 6.0.1

**Comment by SimonAnnetts** [comment]
nugets will be pushed to nuget.org tomorrow after testing.

**Comment by CrispinF** [comment]
@JimKerslake @SimonAnnetts it's only working when there is a signed in user. 

Here's the output script on a page when a user is signed in:
```xml
<!-- Start Analytics.GA4 Tag Helper -->
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-J1FW2YXXXX"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('set', 'page_location', '/');
gtag('set', 'page_referrer', 'https://mysite.com/siteadmin');
gtag('config', 'G-J1FW2YXXXX', { 'user_id': '83bc7688-4b09-400e-a94f-25f3767xxxxx' });
</script>
<!-- End Analytics.GA4 Tag Helper -->
```

And without a signed in user:
```xml
<!-- Start Analytics.GA4 Tag Helper -->
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-J1FW2YXXXX"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('set', 'page_location', '/');
gtag('set', 'page_referrer', 'https://mysite.com/');
gtag('config', 'G-J1FW2YXXXX',  });
</script>
<!-- End Analytics.GA4 Tag Helper -->
```
and we see a console error - this line is badly formed: gtag('config', 'G-J1FW2YXXXX',  });
