### ISSUE TITLE
DefaultNewUserRoles doesn't work from appsettings

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#976]
Specifying this in appsettings in a folder-tenanted site results in a new user being in no roles:

"NewUserOptions": {
"DefaultNewUserRoles": "Authenticated Users,My Other Role"
},

When this config is removed, new users get Authenticated Users role by default.

Not tested in a single-tenant site.

**Comment by JimKerslake** [comment]
@CrispinF 

This isn't broken - though it it mis-documented.

Here it says it needs to be in the MultiTenantOptions - 
https://www.cloudscribe.com/multi-tenant-support - 
which is untrue.
As you quote above, it needs to be in its own section NewUserOptions

But also (as it does say in the docs), it needs to be semicolon-separated, not comma. (?!)
If you use comma it'll be looking in vain for a role called:  Authenticated Users,My Other Role 

So far as I can tell, either commas or semicolons are actually allowed in Role names (!!!)

**Comment by StewartBellamy** [comment]
Maybe the config should really be a json array.

"DefaultNewUserRoles": ["Authenticated Users", "My Other Role", "My ; role"]

**Comment by JimKerslake** [comment]
> Maybe the config should really be a json array.
> 
> "DefaultNewUserRoles": ["Authenticated Users", "My Other Role", "My ; role"]

Yep maybe - though I have had problems dealing with string arrays in json config before now (our logger config) 
since if you ever set it to an empty array in the .prod file, it is regarded as though it were absent and the config wrongly falls through to the underlying appsettings version.

Maybe we should just disallow funky characters in role names...

**Comment by JimKerslake** [comment]
Docs updated as above
